//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionEmpresas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargasArchivos
    {
        public int Id { get; set; }
        public int EmpresaId { get; set; }
        public string NombreArchivo { get; set; }
        public string RutaArchivo { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public string TipoArchivo { get; set; }
        public bool Procesado { get; set; }
    
        public virtual Empresas Empresas { get; set; }
    }
}
