//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionEmpresas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadosFinancieros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstadosFinancieros()
        {
            this.IndicadoresCalculados = new HashSet<IndicadoresCalculados>();
        }
    
        public int EstadoId { get; set; }
        public int EmpresaId { get; set; }
        public System.DateTime Periodo { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaCargue { get; set; }
        public Nullable<decimal> ActivoCorriente { get; set; }
        public Nullable<decimal> PasivoCorriente { get; set; }
        public Nullable<decimal> ActivoTotal { get; set; }
        public Nullable<decimal> PasivoTotal { get; set; }
        public Nullable<decimal> Patrimonio { get; set; }
        public Nullable<decimal> IngresosOperacionales { get; set; }
        public Nullable<decimal> UtilidadBruta { get; set; }
        public Nullable<decimal> UtilidadOperativa { get; set; }
        public Nullable<decimal> UtilidadNeta { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicadoresCalculados> IndicadoresCalculados { get; set; }
    }
}
