//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionEmpresas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicadoresCalculados
    {
        public int Id { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public Nullable<decimal> Indicador1 { get; set; }
        public Nullable<decimal> Indicador2 { get; set; }
        public Nullable<decimal> Indicador3 { get; set; }
        public Nullable<decimal> Indicador4 { get; set; }
        public Nullable<decimal> Indicador5 { get; set; }
    }
}
