//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionEmpresas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicadoresCalculados
    {
        public int IndicadorId { get; set; }
        public int EstadoId { get; set; }
        public Nullable<decimal> LiquidezCorriente { get; set; }
        public Nullable<decimal> RazonEndeudamiento { get; set; }
        public Nullable<decimal> MargenBruto { get; set; }
        public Nullable<decimal> MargenOperativo { get; set; }
        public Nullable<decimal> MargenNeto { get; set; }
        public Nullable<decimal> ROA { get; set; }
        public Nullable<decimal> ROE { get; set; }
        public Nullable<decimal> RotacionActivos { get; set; }
        public Nullable<decimal> CapitalTrabajo { get; set; }
    
        public virtual EstadosFinancieros EstadosFinancieros { get; set; }
    }
}
