//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionEmpresas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbFinanzasEmpresasEntities : DbContext
    {
        public dbFinanzasEmpresasEntities()
            : base("name=dbFinanzasEmpresasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Models.Empresas> Empresas { get; set; }
        public virtual DbSet<Models.EstadosFinancieros> EstadosFinancieros { get; set; }
        public virtual DbSet<Models.IndicadoresCalculados> IndicadoresCalculados { get; set; }
    
        public virtual int CalcularIndicadores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalcularIndicadores");
        }
    }
}
