//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionEmpresas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbFinanzasEmpresaEntities : DbContext
    {
        public dbFinanzasEmpresaEntities()
            : base("name=dbFinanzasEmpresaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<EstadosFinancieros> EstadosFinancieros { get; set; }
        public virtual DbSet<IndicadoresCalculados> IndicadoresCalculados { get; set; }
        public virtual DbSet<CargasArchivos> CargasArchivos { get; set; }
        public virtual DbSet<Indicadores> Indicadores { get; set; }
        public virtual DbSet<Cuentas> Cuentas { get; set; }
    
        public virtual int CalcularIndicadores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalcularIndicadores");
        }
    }
}
