//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionEmpresas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbFinanzasEmpresaEntities : DbContext
    {
        public dbFinanzasEmpresaEntities()
            : base("name=dbFinanzasEmpresaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CargasArchivos> CargasArchivos { get; set; }
        public virtual DbSet<Cuentas> Cuentas { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<EstadosFinancieros> EstadosFinancieros { get; set; }
        public virtual DbSet<Indicadores> Indicadores { get; set; }
    
        public virtual int CalcularIndicadores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalcularIndicadores");
        }
    
        public virtual int SP_InsertarDatosEstadosFinancieros(Nullable<int> empresaId, Nullable<System.DateTime> fecha, Nullable<System.DateTime> periodo, Nullable<decimal> activoCorriente, Nullable<decimal> pasivoCorriente, Nullable<decimal> activoTotal, Nullable<decimal> pasivoTotal, Nullable<decimal> patrimonio, Nullable<decimal> ingresosOperacionales, Nullable<decimal> utilidadBruta, Nullable<decimal> utilidadOperativa, Nullable<decimal> utilidadNeta)
        {
            var empresaIdParameter = empresaId.HasValue ?
                new ObjectParameter("EmpresaId", empresaId) :
                new ObjectParameter("EmpresaId", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var periodoParameter = periodo.HasValue ?
                new ObjectParameter("Periodo", periodo) :
                new ObjectParameter("Periodo", typeof(System.DateTime));
    
            var activoCorrienteParameter = activoCorriente.HasValue ?
                new ObjectParameter("ActivoCorriente", activoCorriente) :
                new ObjectParameter("ActivoCorriente", typeof(decimal));
    
            var pasivoCorrienteParameter = pasivoCorriente.HasValue ?
                new ObjectParameter("PasivoCorriente", pasivoCorriente) :
                new ObjectParameter("PasivoCorriente", typeof(decimal));
    
            var activoTotalParameter = activoTotal.HasValue ?
                new ObjectParameter("ActivoTotal", activoTotal) :
                new ObjectParameter("ActivoTotal", typeof(decimal));
    
            var pasivoTotalParameter = pasivoTotal.HasValue ?
                new ObjectParameter("PasivoTotal", pasivoTotal) :
                new ObjectParameter("PasivoTotal", typeof(decimal));
    
            var patrimonioParameter = patrimonio.HasValue ?
                new ObjectParameter("Patrimonio", patrimonio) :
                new ObjectParameter("Patrimonio", typeof(decimal));
    
            var ingresosOperacionalesParameter = ingresosOperacionales.HasValue ?
                new ObjectParameter("IngresosOperacionales", ingresosOperacionales) :
                new ObjectParameter("IngresosOperacionales", typeof(decimal));
    
            var utilidadBrutaParameter = utilidadBruta.HasValue ?
                new ObjectParameter("UtilidadBruta", utilidadBruta) :
                new ObjectParameter("UtilidadBruta", typeof(decimal));
    
            var utilidadOperativaParameter = utilidadOperativa.HasValue ?
                new ObjectParameter("UtilidadOperativa", utilidadOperativa) :
                new ObjectParameter("UtilidadOperativa", typeof(decimal));
    
            var utilidadNetaParameter = utilidadNeta.HasValue ?
                new ObjectParameter("UtilidadNeta", utilidadNeta) :
                new ObjectParameter("UtilidadNeta", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertarDatosEstadosFinancieros", empresaIdParameter, fechaParameter, periodoParameter, activoCorrienteParameter, pasivoCorrienteParameter, activoTotalParameter, pasivoTotalParameter, patrimonioParameter, ingresosOperacionalesParameter, utilidadBrutaParameter, utilidadOperativaParameter, utilidadNetaParameter);
        }
    }
}
